[package]
name = "weaver"
version.workspace = true
edition.workspace = true
default-run = "wvr"

[[bin]]
name = "wvr"
path = "src/main.rs"

[dependencies]
clap.workspace = true
console.workspace = true
dialoguer.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yml.workspace = true
comfy-table = "8.0"
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
anyhow.workspace = true
weaver-ops.workspace = true
weaver-core.workspace = true
tera.workspace = true
walkdir.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true
