#!/usr/bin/env bash
# Generated by Weaver for app.
# Replaces well-known secret prefixes in tool input with REDACTED before the tool runs.
set -euo pipefail
sed -E \
  -e 's/(sk-ant-[A-Za-z0-9_-]{20,})/REDACTED/g' \
  -e 's/(ghp_[A-Za-z0-9]{20,})/REDACTED/g' \
  -e 's/(AKIA[0-9A-Z]{16})/REDACTED/g'
